-- This migration is intentionally empty.
--
-- The real baseline for this database is the older 202605* migration chain.
-- This duplicate "initial" migration was previously marked as applied only to
-- reconcile local history, so it must remain a no-op for shadow database replays.
